// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Serialization.Serializers.FlatBuffers.VideoModel
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct VideoFlatModel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static VideoFlatModel GetRootAsVideoFlatModel(ByteBuffer _bb) { return GetRootAsVideoFlatModel(_bb, new VideoFlatModel()); }
  public static VideoFlatModel GetRootAsVideoFlatModel(ByteBuffer _bb, VideoFlatModel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public VideoFlatModel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public FlatBuffers.Domain.VideoModel.SocialInfoFlatModel? SocialInfo { get { int o = __p.__offset(4); return o != 0 ? (FlatBuffers.Domain.VideoModel.SocialInfoFlatModel?)(new FlatBuffers.Domain.VideoModel.SocialInfoFlatModel()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public FlatBuffers.Domain.VideoModel.VideoInfoFlatModel? VideoInfo { get { int o = __p.__offset(6); return o != 0 ? (FlatBuffers.Domain.VideoModel.VideoInfoFlatModel?)(new FlatBuffers.Domain.VideoModel.VideoInfoFlatModel()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }
  public FlatBuffers.Domain.VideoModel.ChannelFlatModel? Channel { get { int o = __p.__offset(8); return o != 0 ? (FlatBuffers.Domain.VideoModel.ChannelFlatModel?)(new FlatBuffers.Domain.VideoModel.ChannelFlatModel()).__assign(__p.__indirect(o + __p.bb_pos), __p.bb) : null; } }

  public static Offset<FlatBuffers.Domain.VideoModel.VideoFlatModel> CreateVideoFlatModel(FlatBufferBuilder builder,
      Offset<FlatBuffers.Domain.VideoModel.SocialInfoFlatModel> social_infoOffset = default(Offset<FlatBuffers.Domain.VideoModel.SocialInfoFlatModel>),
      Offset<FlatBuffers.Domain.VideoModel.VideoInfoFlatModel> video_infoOffset = default(Offset<FlatBuffers.Domain.VideoModel.VideoInfoFlatModel>),
      Offset<FlatBuffers.Domain.VideoModel.ChannelFlatModel> channelOffset = default(Offset<FlatBuffers.Domain.VideoModel.ChannelFlatModel>)) {
    builder.StartTable(3);
    VideoFlatModel.AddChannel(builder, channelOffset);
    VideoFlatModel.AddVideoInfo(builder, video_infoOffset);
    VideoFlatModel.AddSocialInfo(builder, social_infoOffset);
    return VideoFlatModel.EndVideoFlatModel(builder);
  }

  public static void StartVideoFlatModel(FlatBufferBuilder builder) { builder.StartTable(3); }
  public static void AddSocialInfo(FlatBufferBuilder builder, Offset<FlatBuffers.Domain.VideoModel.SocialInfoFlatModel> socialInfoOffset) { builder.AddOffset(0, socialInfoOffset.Value, 0); }
  public static void AddVideoInfo(FlatBufferBuilder builder, Offset<FlatBuffers.Domain.VideoModel.VideoInfoFlatModel> videoInfoOffset) { builder.AddOffset(1, videoInfoOffset.Value, 0); }
  public static void AddChannel(FlatBufferBuilder builder, Offset<FlatBuffers.Domain.VideoModel.ChannelFlatModel> channelOffset) { builder.AddOffset(2, channelOffset.Value, 0); }
  public static Offset<FlatBuffers.Domain.VideoModel.VideoFlatModel> EndVideoFlatModel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatBuffers.Domain.VideoModel.VideoFlatModel>(o);
  }
  public static void FinishVideoFlatModelBuffer(FlatBufferBuilder builder, Offset<FlatBuffers.Domain.VideoModel.VideoFlatModel> offset) { builder.Finish(offset.Value); }
  public static void FinishSizePrefixedVideoFlatModelBuffer(FlatBufferBuilder builder, Offset<FlatBuffers.Domain.VideoModel.VideoFlatModel> offset) { builder.FinishSizePrefixed(offset.Value); }
}


}
