// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBuffersModels
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SocialInfoFlatModel : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_5_26(); }
  public static SocialInfoFlatModel GetRootAsSocialInfoFlatModel(ByteBuffer _bb) { return GetRootAsSocialInfoFlatModel(_bb, new SocialInfoFlatModel()); }
  public static SocialInfoFlatModel GetRootAsSocialInfoFlatModel(ByteBuffer _bb, SocialInfoFlatModel obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SocialInfoFlatModel __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Likes { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateLikes(int likes) { int o = __p.__offset(4); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, likes); return true; } else { return false; } }
  public int Dislikes { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateDislikes(int dislikes) { int o = __p.__offset(6); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, dislikes); return true; } else { return false; } }
  public string Comments(int j) { int o = __p.__offset(8); return o != 0 ? __p.__string(__p.__vector(o) + j * 4) : null; }
  public int CommentsLength { get { int o = __p.__offset(8); return o != 0 ? __p.__vector_len(o) : 0; } }
  public int Views { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public bool MutateViews(int views) { int o = __p.__offset(10); if (o != 0) { __p.bb.PutInt(o + __p.bb_pos, views); return true; } else { return false; } }

  public static Offset<FlatBuffersModels.SocialInfoFlatModel> CreateSocialInfoFlatModel(FlatBufferBuilder builder,
      int likes = 0,
      int dislikes = 0,
      VectorOffset commentsOffset = default(VectorOffset),
      int views = 0) {
    builder.StartTable(4);
    SocialInfoFlatModel.AddViews(builder, views);
    SocialInfoFlatModel.AddComments(builder, commentsOffset);
    SocialInfoFlatModel.AddDislikes(builder, dislikes);
    SocialInfoFlatModel.AddLikes(builder, likes);
    return SocialInfoFlatModel.EndSocialInfoFlatModel(builder);
  }

  public static void StartSocialInfoFlatModel(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddLikes(FlatBufferBuilder builder, int likes) { builder.AddInt(0, likes, 0); }
  public static void AddDislikes(FlatBufferBuilder builder, int dislikes) { builder.AddInt(1, dislikes, 0); }
  public static void AddComments(FlatBufferBuilder builder, VectorOffset commentsOffset) { builder.AddOffset(2, commentsOffset.Value, 0); }
  public static VectorOffset CreateCommentsVector(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); for (int i = data.Length - 1; i >= 0; i--) builder.AddOffset(data[i].Value); return builder.EndVector(); }
  public static VectorOffset CreateCommentsVectorBlock(FlatBufferBuilder builder, StringOffset[] data) { builder.StartVector(4, data.Length, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCommentsVectorBlock(FlatBufferBuilder builder, ArraySegment<StringOffset> data) { builder.StartVector(4, data.Count, 4); builder.Add(data); return builder.EndVector(); }
  public static VectorOffset CreateCommentsVectorBlock(FlatBufferBuilder builder, IntPtr dataPtr, int sizeInBytes) { builder.StartVector(1, sizeInBytes, 1); builder.Add<StringOffset>(dataPtr, sizeInBytes); return builder.EndVector(); }
  public static void StartCommentsVector(FlatBufferBuilder builder, int numElems) { builder.StartVector(4, numElems, 4); }
  public static void AddViews(FlatBufferBuilder builder, int views) { builder.AddInt(3, views, 0); }
  public static Offset<FlatBuffersModels.SocialInfoFlatModel> EndSocialInfoFlatModel(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatBuffersModels.SocialInfoFlatModel>(o);
  }
}


static public class SocialInfoFlatModelVerify
{
  static public bool Verify(Google.FlatBuffers.Verifier verifier, uint tablePos)
  {
    return verifier.VerifyTableStart(tablePos)
      && verifier.VerifyField(tablePos, 4 /*Likes*/, 4 /*int*/, 4, false)
      && verifier.VerifyField(tablePos, 6 /*Dislikes*/, 4 /*int*/, 4, false)
      && verifier.VerifyVectorOfStrings(tablePos, 8 /*Comments*/, false)
      && verifier.VerifyField(tablePos, 10 /*Views*/, 4 /*int*/, 4, false)
      && verifier.VerifyTableEnd(tablePos);
  }
}

}
