// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace avroObjects
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class SocialInfo : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse("{\"type\":\"record\",\"name\":\"SocialInfo\",\"namespace\":\"avroObjects\",\"fields\":[{\"name\":" +
				"\"Likes\",\"type\":\"int\"},{\"name\":\"Dislikes\",\"type\":\"int\"},{\"name\":\"Comments\",\"type\"" +
				":{\"type\":\"array\",\"items\":\"string\"}},{\"name\":\"Views\",\"type\":\"int\"}]}");
		private int _Likes;
		private int _Dislikes;
		private IList<System.String> _Comments;
		private int _Views;
		public virtual Schema Schema
		{
			get
			{
				return SocialInfo._SCHEMA;
			}
		}
		public int Likes
		{
			get
			{
				return this._Likes;
			}
			set
			{
				this._Likes = value;
			}
		}
		public int Dislikes
		{
			get
			{
				return this._Dislikes;
			}
			set
			{
				this._Dislikes = value;
			}
		}
		public IList<System.String> Comments
		{
			get
			{
				return this._Comments;
			}
			set
			{
				this._Comments = value;
			}
		}
		public int Views
		{
			get
			{
				return this._Views;
			}
			set
			{
				this._Views = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.Likes;
			case 1: return this.Dislikes;
			case 2: return this.Comments;
			case 3: return this.Views;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.Likes = (System.Int32)fieldValue; break;
			case 1: this.Dislikes = (System.Int32)fieldValue; break;
			case 2: this.Comments = (IList<System.String>)fieldValue; break;
			case 3: this.Views = (System.Int32)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
