// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace avroObjects
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public partial class Video : ISpecificRecord
	{
		public static Schema _SCHEMA = Schema.Parse(@"{""type"":""record"",""name"":""Video"",""namespace"":""avroObjects"",""fields"":[{""name"":""VideoId"",""type"":""string""},{""name"":""Url"",""type"":""string""},{""name"":""Channel"",""type"":{""type"":""record"",""name"":""Channel"",""namespace"":""avroObjects"",""fields"":[{""name"":""Name"",""type"":""string""},{""name"":""Subscribers"",""type"":""int""},{""name"":""ChannelId"",""type"":""string""}]}},{""name"":""SocialInfo"",""type"":{""type"":""record"",""name"":""SocialInfo"",""namespace"":""avroObjects"",""fields"":[{""name"":""Likes"",""type"":""int""},{""name"":""Dislikes"",""type"":""int""},{""name"":""Comments"",""type"":{""type"":""array"",""items"":""string""}},{""name"":""Views"",""type"":""int""}]}},{""name"":""VideoInfo"",""type"":{""type"":""record"",""name"":""VideoInfo"",""namespace"":""avroObjects"",""fields"":[{""name"":""Duration"",""type"":""long""},{""name"":""Description"",""type"":""string""},{""name"":""Size"",""type"":""long""},{""name"":""Qualities"",""type"":{""type"":""array"",""items"":{""type"":""enum"",""name"":""VideoQualities"",""namespace"":""avroObjects"",""symbols"":[""Undefined"",""Lowest"",""Low"",""Medium"",""SD"",""HD"",""TwoK"",""FourK""]}}}]}}]}");
		private string _VideoId;
		private string _Url;
		private avroObjects.Channel _Channel;
		private avroObjects.SocialInfo _SocialInfo;
		private avroObjects.VideoInfo _VideoInfo;
		public virtual Schema Schema
		{
			get
			{
				return Video._SCHEMA;
			}
		}
		public string VideoId
		{
			get
			{
				return this._VideoId;
			}
			set
			{
				this._VideoId = value;
			}
		}
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				this._Url = value;
			}
		}
		public avroObjects.Channel Channel
		{
			get
			{
				return this._Channel;
			}
			set
			{
				this._Channel = value;
			}
		}
		public avroObjects.SocialInfo SocialInfo
		{
			get
			{
				return this._SocialInfo;
			}
			set
			{
				this._SocialInfo = value;
			}
		}
		public avroObjects.VideoInfo VideoInfo
		{
			get
			{
				return this._VideoInfo;
			}
			set
			{
				this._VideoInfo = value;
			}
		}
		public virtual object Get(int fieldPos)
		{
			switch (fieldPos)
			{
			case 0: return this.VideoId;
			case 1: return this.Url;
			case 2: return this.Channel;
			case 3: return this.SocialInfo;
			case 4: return this.VideoInfo;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Get()");
			};
		}
		public virtual void Put(int fieldPos, object fieldValue)
		{
			switch (fieldPos)
			{
			case 0: this.VideoId = (System.String)fieldValue; break;
			case 1: this.Url = (System.String)fieldValue; break;
			case 2: this.Channel = (avroObjects.Channel)fieldValue; break;
			case 3: this.SocialInfo = (avroObjects.SocialInfo)fieldValue; break;
			case 4: this.VideoInfo = (avroObjects.VideoInfo)fieldValue; break;
			default: throw new AvroRuntimeException("Bad index " + fieldPos + " in Put()");
			};
		}
	}
}
