// ------------------------------------------------------------------------------
// <auto-generated>
//    Generated by avrogen, version 1.7.7.5
//    Changes to this file may cause incorrect behavior and will be lost if code
//    is regenerated
// </auto-generated>
// ------------------------------------------------------------------------------
namespace avroObjects
{
	using System;
	using System.Collections.Generic;
	using System.Text;
	using global::Avro;
	using global::Avro.Specific;
	
	public enum VideoQualities
	{
        Undefined = 0,
        Lowest = 144,
        Low = 360,
        Medium = 480,
        SD = 720,
        HD = 1080,
        TwoK = 1440,
        FourK = 2160,
    }
}
