// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace Serialization.Domain.FlatBuffers.VideoModel
{

public enum VideoQualityFlatModel : short
{
  Lowest = 144,
  Low = 360,
  Medium = 480,
  SD = 720,
  HD = 1080,
  TwoK = 1440,
  FourK = 2160,
};


}
