// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: protoObjects.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace ProtoObjects {

  /// <summary>Holder for reflection information generated from protoObjects.proto</summary>
  public static partial class ProtoObjectsReflection {

    #region Descriptor
    /// <summary>File descriptor for protoObjects.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ProtoObjectsReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "ChJwcm90b09iamVjdHMucHJvdG8SDHByb3RvT2JqZWN0cyI/CgdDaGFubmVs",
            "EgwKBE5hbWUYASABKAkSEwoLU3Vic2NyaWJlcnMYAiABKA0SEQoJQ2hhbm5l",
            "bElkGAMgASgJIk4KClNvY2lhbEluZm8SDQoFTGlrZXMYASABKA0SEAoIRGlz",
            "bGlrZXMYAiABKA0SEAoIQ29tbWVudHMYAyADKAkSDQoFVmlld3MYBCABKA0i",
            "6QEKCVZpZGVvSW5mbxIQCghEdXJhdGlvbhgBIAEoBBITCgtEZXNjcmlwdGlv",
            "bhgCIAEoCRIMCgRTaXplGAMgASgEEjkKCVF1YWxpdGllcxgEIAMoDjImLnBy",
            "b3RvT2JqZWN0cy5WaWRlb0luZm8uVmlkZW9RdWFsaXRpZXMibAoOVmlkZW9R",
            "dWFsaXRpZXMSDQoJVW5kZWZpbmVkEAASCwoGTG93ZXN0EJABEggKA0xvdxDo",
            "AhILCgZNZWRpdW0Q4AMSBwoCU0QQ0AUSBwoCSEQQuAgSCQoEVHdvSxCgCxIK",
            "CgVGb3VySxDwECKnAQoFVmlkZW8SDwoHVmlkZW9JZBgBIAEoCRILCgNVcmwY",
            "AiABKAkSJgoHQ2hhbm5lbBgDIAEoCzIVLnByb3RvT2JqZWN0cy5DaGFubmVs",
            "EiwKClNvY2lhbEluZm8YBCABKAsyGC5wcm90b09iamVjdHMuU29jaWFsSW5m",
            "bxIqCglWaWRlb0luZm8YBSABKAsyFy5wcm90b09iamVjdHMuVmlkZW9JbmZv",
            "YgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoObjects.Channel), global::ProtoObjects.Channel.Parser, new[]{ "Name", "Subscribers", "ChannelId" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoObjects.SocialInfo), global::ProtoObjects.SocialInfo.Parser, new[]{ "Likes", "Dislikes", "Comments", "Views" }, null, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoObjects.VideoInfo), global::ProtoObjects.VideoInfo.Parser, new[]{ "Duration", "Description", "Size", "Qualities" }, null, new[]{ typeof(global::ProtoObjects.VideoInfo.Types.VideoQualities) }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::ProtoObjects.Video), global::ProtoObjects.Video.Parser, new[]{ "VideoId", "Url", "Channel", "SocialInfo", "VideoInfo" }, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class Channel : pb::IMessage<Channel>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Channel> _parser = new pb::MessageParser<Channel>(() => new Channel());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Channel> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoObjects.ProtoObjectsReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Channel() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Channel(Channel other) : this() {
      name_ = other.name_;
      subscribers_ = other.subscribers_;
      channelId_ = other.channelId_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Channel Clone() {
      return new Channel(this);
    }

    /// <summary>Field number for the "Name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Subscribers" field.</summary>
    public const int SubscribersFieldNumber = 2;
    private uint subscribers_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Subscribers {
      get { return subscribers_; }
      set {
        subscribers_ = value;
      }
    }

    /// <summary>Field number for the "ChannelId" field.</summary>
    public const int ChannelIdFieldNumber = 3;
    private string channelId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ChannelId {
      get { return channelId_; }
      set {
        channelId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Channel);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Channel other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Subscribers != other.Subscribers) return false;
      if (ChannelId != other.ChannelId) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Subscribers != 0) hash ^= Subscribers.GetHashCode();
      if (ChannelId.Length != 0) hash ^= ChannelId.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Subscribers != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Subscribers);
      }
      if (ChannelId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ChannelId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Subscribers != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Subscribers);
      }
      if (ChannelId.Length != 0) {
        output.WriteRawTag(26);
        output.WriteString(ChannelId);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Subscribers != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Subscribers);
      }
      if (ChannelId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ChannelId);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Channel other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Subscribers != 0) {
        Subscribers = other.Subscribers;
      }
      if (other.ChannelId.Length != 0) {
        ChannelId = other.ChannelId;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Subscribers = input.ReadUInt32();
            break;
          }
          case 26: {
            ChannelId = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Subscribers = input.ReadUInt32();
            break;
          }
          case 26: {
            ChannelId = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class SocialInfo : pb::IMessage<SocialInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<SocialInfo> _parser = new pb::MessageParser<SocialInfo>(() => new SocialInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<SocialInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoObjects.ProtoObjectsReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SocialInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SocialInfo(SocialInfo other) : this() {
      likes_ = other.likes_;
      dislikes_ = other.dislikes_;
      comments_ = other.comments_.Clone();
      views_ = other.views_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public SocialInfo Clone() {
      return new SocialInfo(this);
    }

    /// <summary>Field number for the "Likes" field.</summary>
    public const int LikesFieldNumber = 1;
    private uint likes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Likes {
      get { return likes_; }
      set {
        likes_ = value;
      }
    }

    /// <summary>Field number for the "Dislikes" field.</summary>
    public const int DislikesFieldNumber = 2;
    private uint dislikes_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Dislikes {
      get { return dislikes_; }
      set {
        dislikes_ = value;
      }
    }

    /// <summary>Field number for the "Comments" field.</summary>
    public const int CommentsFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_comments_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> comments_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Comments {
      get { return comments_; }
    }

    /// <summary>Field number for the "Views" field.</summary>
    public const int ViewsFieldNumber = 4;
    private uint views_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public uint Views {
      get { return views_; }
      set {
        views_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as SocialInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(SocialInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Likes != other.Likes) return false;
      if (Dislikes != other.Dislikes) return false;
      if(!comments_.Equals(other.comments_)) return false;
      if (Views != other.Views) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Likes != 0) hash ^= Likes.GetHashCode();
      if (Dislikes != 0) hash ^= Dislikes.GetHashCode();
      hash ^= comments_.GetHashCode();
      if (Views != 0) hash ^= Views.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Likes != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Likes);
      }
      if (Dislikes != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Dislikes);
      }
      comments_.WriteTo(output, _repeated_comments_codec);
      if (Views != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Views);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Likes != 0) {
        output.WriteRawTag(8);
        output.WriteUInt32(Likes);
      }
      if (Dislikes != 0) {
        output.WriteRawTag(16);
        output.WriteUInt32(Dislikes);
      }
      comments_.WriteTo(ref output, _repeated_comments_codec);
      if (Views != 0) {
        output.WriteRawTag(32);
        output.WriteUInt32(Views);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Likes != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Likes);
      }
      if (Dislikes != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Dislikes);
      }
      size += comments_.CalculateSize(_repeated_comments_codec);
      if (Views != 0) {
        size += 1 + pb::CodedOutputStream.ComputeUInt32Size(Views);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(SocialInfo other) {
      if (other == null) {
        return;
      }
      if (other.Likes != 0) {
        Likes = other.Likes;
      }
      if (other.Dislikes != 0) {
        Dislikes = other.Dislikes;
      }
      comments_.Add(other.comments_);
      if (other.Views != 0) {
        Views = other.Views;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Likes = input.ReadUInt32();
            break;
          }
          case 16: {
            Dislikes = input.ReadUInt32();
            break;
          }
          case 26: {
            comments_.AddEntriesFrom(input, _repeated_comments_codec);
            break;
          }
          case 32: {
            Views = input.ReadUInt32();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Likes = input.ReadUInt32();
            break;
          }
          case 16: {
            Dislikes = input.ReadUInt32();
            break;
          }
          case 26: {
            comments_.AddEntriesFrom(ref input, _repeated_comments_codec);
            break;
          }
          case 32: {
            Views = input.ReadUInt32();
            break;
          }
        }
      }
    }
    #endif

  }

  public sealed partial class VideoInfo : pb::IMessage<VideoInfo>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<VideoInfo> _parser = new pb::MessageParser<VideoInfo>(() => new VideoInfo());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<VideoInfo> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoObjects.ProtoObjectsReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VideoInfo() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VideoInfo(VideoInfo other) : this() {
      duration_ = other.duration_;
      description_ = other.description_;
      size_ = other.size_;
      qualities_ = other.qualities_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public VideoInfo Clone() {
      return new VideoInfo(this);
    }

    /// <summary>Field number for the "Duration" field.</summary>
    public const int DurationFieldNumber = 1;
    private ulong duration_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Duration {
      get { return duration_; }
      set {
        duration_ = value;
      }
    }

    /// <summary>Field number for the "Description" field.</summary>
    public const int DescriptionFieldNumber = 2;
    private string description_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Size" field.</summary>
    public const int SizeFieldNumber = 3;
    private ulong size_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public ulong Size {
      get { return size_; }
      set {
        size_ = value;
      }
    }

    /// <summary>Field number for the "Qualities" field.</summary>
    public const int QualitiesFieldNumber = 4;
    private static readonly pb::FieldCodec<global::ProtoObjects.VideoInfo.Types.VideoQualities> _repeated_qualities_codec
        = pb::FieldCodec.ForEnum(34, x => (int) x, x => (global::ProtoObjects.VideoInfo.Types.VideoQualities) x);
    private readonly pbc::RepeatedField<global::ProtoObjects.VideoInfo.Types.VideoQualities> qualities_ = new pbc::RepeatedField<global::ProtoObjects.VideoInfo.Types.VideoQualities>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<global::ProtoObjects.VideoInfo.Types.VideoQualities> Qualities {
      get { return qualities_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as VideoInfo);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(VideoInfo other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Duration != other.Duration) return false;
      if (Description != other.Description) return false;
      if (Size != other.Size) return false;
      if(!qualities_.Equals(other.qualities_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Duration != 0UL) hash ^= Duration.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      if (Size != 0UL) hash ^= Size.GetHashCode();
      hash ^= qualities_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Duration != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Duration);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Description);
      }
      if (Size != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(Size);
      }
      qualities_.WriteTo(output, _repeated_qualities_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Duration != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(Duration);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Description);
      }
      if (Size != 0UL) {
        output.WriteRawTag(24);
        output.WriteUInt64(Size);
      }
      qualities_.WriteTo(ref output, _repeated_qualities_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Duration != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Duration);
      }
      if (Description.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      if (Size != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(Size);
      }
      size += qualities_.CalculateSize(_repeated_qualities_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(VideoInfo other) {
      if (other == null) {
        return;
      }
      if (other.Duration != 0UL) {
        Duration = other.Duration;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      if (other.Size != 0UL) {
        Size = other.Size;
      }
      qualities_.Add(other.qualities_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Duration = input.ReadUInt64();
            break;
          }
          case 18: {
            Description = input.ReadString();
            break;
          }
          case 24: {
            Size = input.ReadUInt64();
            break;
          }
          case 34:
          case 32: {
            qualities_.AddEntriesFrom(input, _repeated_qualities_codec);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Duration = input.ReadUInt64();
            break;
          }
          case 18: {
            Description = input.ReadString();
            break;
          }
          case 24: {
            Size = input.ReadUInt64();
            break;
          }
          case 34:
          case 32: {
            qualities_.AddEntriesFrom(ref input, _repeated_qualities_codec);
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the VideoInfo message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      public enum VideoQualities {
        [pbr::OriginalName("Undefined")] Undefined = 0,
        [pbr::OriginalName("Lowest")] Lowest = 144,
        [pbr::OriginalName("Low")] Low = 360,
        [pbr::OriginalName("Medium")] Medium = 480,
        [pbr::OriginalName("SD")] Sd = 720,
        [pbr::OriginalName("HD")] Hd = 1080,
        [pbr::OriginalName("TwoK")] TwoK = 1440,
        [pbr::OriginalName("FourK")] FourK = 2160,
      }

    }
    #endregion

  }

  public sealed partial class Video : pb::IMessage<Video>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<Video> _parser = new pb::MessageParser<Video>(() => new Video());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<Video> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::ProtoObjects.ProtoObjectsReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Video() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Video(Video other) : this() {
      videoId_ = other.videoId_;
      url_ = other.url_;
      channel_ = other.channel_ != null ? other.channel_.Clone() : null;
      socialInfo_ = other.socialInfo_ != null ? other.socialInfo_.Clone() : null;
      videoInfo_ = other.videoInfo_ != null ? other.videoInfo_.Clone() : null;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public Video Clone() {
      return new Video(this);
    }

    /// <summary>Field number for the "VideoId" field.</summary>
    public const int VideoIdFieldNumber = 1;
    private string videoId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string VideoId {
      get { return videoId_; }
      set {
        videoId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Url" field.</summary>
    public const int UrlFieldNumber = 2;
    private string url_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Url {
      get { return url_; }
      set {
        url_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "Channel" field.</summary>
    public const int ChannelFieldNumber = 3;
    private global::ProtoObjects.Channel channel_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ProtoObjects.Channel Channel {
      get { return channel_; }
      set {
        channel_ = value;
      }
    }

    /// <summary>Field number for the "SocialInfo" field.</summary>
    public const int SocialInfoFieldNumber = 4;
    private global::ProtoObjects.SocialInfo socialInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ProtoObjects.SocialInfo SocialInfo {
      get { return socialInfo_; }
      set {
        socialInfo_ = value;
      }
    }

    /// <summary>Field number for the "VideoInfo" field.</summary>
    public const int VideoInfoFieldNumber = 5;
    private global::ProtoObjects.VideoInfo videoInfo_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::ProtoObjects.VideoInfo VideoInfo {
      get { return videoInfo_; }
      set {
        videoInfo_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as Video);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(Video other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (VideoId != other.VideoId) return false;
      if (Url != other.Url) return false;
      if (!object.Equals(Channel, other.Channel)) return false;
      if (!object.Equals(SocialInfo, other.SocialInfo)) return false;
      if (!object.Equals(VideoInfo, other.VideoInfo)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (VideoId.Length != 0) hash ^= VideoId.GetHashCode();
      if (Url.Length != 0) hash ^= Url.GetHashCode();
      if (channel_ != null) hash ^= Channel.GetHashCode();
      if (socialInfo_ != null) hash ^= SocialInfo.GetHashCode();
      if (videoInfo_ != null) hash ^= VideoInfo.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (VideoId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(VideoId);
      }
      if (Url.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Url);
      }
      if (channel_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Channel);
      }
      if (socialInfo_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(SocialInfo);
      }
      if (videoInfo_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(VideoInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (VideoId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(VideoId);
      }
      if (Url.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(Url);
      }
      if (channel_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(Channel);
      }
      if (socialInfo_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(SocialInfo);
      }
      if (videoInfo_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(VideoInfo);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (VideoId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(VideoId);
      }
      if (Url.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Url);
      }
      if (channel_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(Channel);
      }
      if (socialInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(SocialInfo);
      }
      if (videoInfo_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(VideoInfo);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(Video other) {
      if (other == null) {
        return;
      }
      if (other.VideoId.Length != 0) {
        VideoId = other.VideoId;
      }
      if (other.Url.Length != 0) {
        Url = other.Url;
      }
      if (other.channel_ != null) {
        if (channel_ == null) {
          Channel = new global::ProtoObjects.Channel();
        }
        Channel.MergeFrom(other.Channel);
      }
      if (other.socialInfo_ != null) {
        if (socialInfo_ == null) {
          SocialInfo = new global::ProtoObjects.SocialInfo();
        }
        SocialInfo.MergeFrom(other.SocialInfo);
      }
      if (other.videoInfo_ != null) {
        if (videoInfo_ == null) {
          VideoInfo = new global::ProtoObjects.VideoInfo();
        }
        VideoInfo.MergeFrom(other.VideoInfo);
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            VideoId = input.ReadString();
            break;
          }
          case 18: {
            Url = input.ReadString();
            break;
          }
          case 26: {
            if (channel_ == null) {
              Channel = new global::ProtoObjects.Channel();
            }
            input.ReadMessage(Channel);
            break;
          }
          case 34: {
            if (socialInfo_ == null) {
              SocialInfo = new global::ProtoObjects.SocialInfo();
            }
            input.ReadMessage(SocialInfo);
            break;
          }
          case 42: {
            if (videoInfo_ == null) {
              VideoInfo = new global::ProtoObjects.VideoInfo();
            }
            input.ReadMessage(VideoInfo);
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 10: {
            VideoId = input.ReadString();
            break;
          }
          case 18: {
            Url = input.ReadString();
            break;
          }
          case 26: {
            if (channel_ == null) {
              Channel = new global::ProtoObjects.Channel();
            }
            input.ReadMessage(Channel);
            break;
          }
          case 34: {
            if (socialInfo_ == null) {
              SocialInfo = new global::ProtoObjects.SocialInfo();
            }
            input.ReadMessage(SocialInfo);
            break;
          }
          case 42: {
            if (videoInfo_ == null) {
              VideoInfo = new global::ProtoObjects.VideoInfo();
            }
            input.ReadMessage(VideoInfo);
            break;
          }
        }
      }
    }
    #endif

  }

  #endregion

}

#endregion Designer generated code
