/**
 * <auto-generated>
 * Autogenerated by Thrift Compiler (0.19.0)
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 * </auto-generated>
 */
using System;
using System.Collections;
using System.Collections.Generic;
using System.Text;
using System.IO;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Extensions.Logging;
using Thrift;
using Thrift.Collections;
using Thrift.Protocol;


#pragma warning disable IDE0079  // remove unnecessary pragmas
#pragma warning disable IDE0017  // object init can be simplified
#pragma warning disable IDE0028  // collection init can be simplified
#pragma warning disable IDE1006  // parts of the code use IDL spelling
#pragma warning disable CA1822   // empty DeepCopy() methods still non-static
#pragma warning disable IDE0083  // pattern matching "that is not SomeType" requires net5.0 but we still support earlier versions

namespace thriftObjects
{
  public static class thriftObjectsExtensions
  {
    public static bool Equals(this List<global::thriftObjects.VideoQualities> instance, object that)
    {
      if (!(that is List<global::thriftObjects.VideoQualities> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<global::thriftObjects.VideoQualities> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static List<global::thriftObjects.VideoQualities> DeepCopy(this List<global::thriftObjects.VideoQualities> source)
    {
      if (source == null)
        return null;

      var tmp28 = new List<global::thriftObjects.VideoQualities>(source.Count);
      foreach (var elem in source)
        tmp28.Add(elem);
      return tmp28;
    }


    public static bool Equals(this List<string> instance, object that)
    {
      if (!(that is List<string> other)) return false;
      if (ReferenceEquals(instance, other)) return true;

      return TCollections.Equals(instance, other);
    }


    public static int GetHashCode(this List<string> instance)
    {
      return TCollections.GetHashCode(instance);
    }


    public static List<string> DeepCopy(this List<string> source)
    {
      if (source == null)
        return null;

      var tmp29 = new List<string>(source.Count);
      foreach (var elem in source)
        tmp29.Add((elem != null) ? elem : null);
      return tmp29;
    }


  }
}
