// <auto-generated>
//  automatically generated by the FlatBuffers compiler, do not modify
// </auto-generated>

namespace FlatBuffers.Receiver.Video
{

using global::System;
using global::System.Collections.Generic;
using global::Google.FlatBuffers;

public struct SocialInfo : IFlatbufferObject
{
  private Table __p;
  public ByteBuffer ByteBuffer { get { return __p.bb; } }
  public static void ValidateVersion() { FlatBufferConstants.FLATBUFFERS_23_3_3(); }
  public static SocialInfo GetRootAsSocialInfo(ByteBuffer _bb) { return GetRootAsSocialInfo(_bb, new SocialInfo()); }
  public static SocialInfo GetRootAsSocialInfo(ByteBuffer _bb, SocialInfo obj) { return (obj.__assign(_bb.GetInt(_bb.Position) + _bb.Position, _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __p = new Table(_i, _bb); }
  public SocialInfo __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public int Likes { get { int o = __p.__offset(4); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Dislikes { get { int o = __p.__offset(6); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Comments { get { int o = __p.__offset(8); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }
  public int Views { get { int o = __p.__offset(10); return o != 0 ? __p.bb.GetInt(o + __p.bb_pos) : (int)0; } }

  public static Offset<FlatBuffers.Receiver.Video.SocialInfo> CreateSocialInfo(FlatBufferBuilder builder,
      int likes = 0,
      int dislikes = 0,
      int comments = 0,
      int views = 0) {
    builder.StartTable(4);
    SocialInfo.AddViews(builder, views);
    SocialInfo.AddComments(builder, comments);
    SocialInfo.AddDislikes(builder, dislikes);
    SocialInfo.AddLikes(builder, likes);
    return SocialInfo.EndSocialInfo(builder);
  }

  public static void StartSocialInfo(FlatBufferBuilder builder) { builder.StartTable(4); }
  public static void AddLikes(FlatBufferBuilder builder, int likes) { builder.AddInt(0, likes, 0); }
  public static void AddDislikes(FlatBufferBuilder builder, int dislikes) { builder.AddInt(1, dislikes, 0); }
  public static void AddComments(FlatBufferBuilder builder, int comments) { builder.AddInt(2, comments, 0); }
  public static void AddViews(FlatBufferBuilder builder, int views) { builder.AddInt(3, views, 0); }
  public static Offset<FlatBuffers.Receiver.Video.SocialInfo> EndSocialInfo(FlatBufferBuilder builder) {
    int o = builder.EndTable();
    return new Offset<FlatBuffers.Receiver.Video.SocialInfo>(o);
  }
}


}
